version: ${project.version}

debug: false

custom-storage:
  # 自定义存储位置
  # 默认存储位置为 “插件文件夹”/prefixes
  # 可以规定到远程文件夹中去寻找前缀相关的设定
  # 支持绝对文件路径，如 "/etc/minecraft/configurations/prefixes/"
  enable: false # 是否启用
  path: "prefixes/" # 一定要指向一个文件夹！

functions:
  OnNamePrefix: true # 是否给头顶上添加前缀，该方法用到了头顶的那个计分板，如有冲突请关掉哦~
  autoUsePrefix: true # 自动前缀显示 当玩家没有自己选择一个前缀的时候，会自动使用所拥有的的前缀中权重最高的那一个
  chat:
    # 聊天功能
    # - 我不推荐使用本插件的聊天功能，而是建议使用其他的聊天插件。
    # - 本插件仅仅提供了**最基本**的格式变量支持，不包含其他任何功能。
    # - 注意聊天格式需要遵守Bukkit原格式，即不得缺失 “%1$s” 和 “%2$s” 。
    # - 本插件的聊天功能不影响其他插件对聊天事件的操作。
    enable: false # 是否启用
    format: "<%UserPrefix_prefix%%1$s> %2$s" #聊天的格式，注意 “%1$s” 和 “%2$s” 不可缺少，分别代表 玩家名 与 消息内容 。

GUI:
  title: "&f&l我的前缀 &8| 列表"
  items:
    # 【必须】 GUI中可能存在的其他物品
    next-page: # 下一页物品，如果没有下一页则不显示
      ==: org.bukkit.inventory.ItemStack
      type: ARROW
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "§f下一页"
        lore:
          - ""
          - "§f右键可前往最后一页哦~"
    previous-page: # 上一页物品，如果没有上一页则不显示
      ==: org.bukkit.inventory.ItemStack
      type: ARROW
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "§f上一页"
        lore:
          - ""
          - "§f右键可前往第一页哦~"

Sounds: #相关的声音，注释掉则不播放声音 格式为 【声音名:音量:音调】 或 【声音名:音量】 或 【声音名】
  openGUI: "BLOCK_NOTE_BLOCK_PLING:1:1"
  guiClick: "UI_BUTTON_CLICK"
  prefixChange: "ENTITY_VILLAGER_YES"
  prefixExpired: "ENTITY_VILLAGER_NO"

# 默认前缀的配置
# 默认前缀的权重为0哦
defaultPrefix:
  name: "默认前缀"
  content: "&b"
  itemNotUsing:
    ==: org.bukkit.inventory.ItemStack
    type: NAME_TAG
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: "§f默认玩家前缀 §f(点击切换)"
      lore:
        - ""
        - "§a➥ 点击切换到该前缀"
  itemUsing:
    ==: org.bukkit.inventory.ItemStack
    type: NAME_TAG
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: "§f默认玩家前缀"
      lore:
        - ""
        - "§a✔ 您正在使用该前缀"